theme: jekyll-theme-architect
title: Phasmophobia Guide
description: A guide to the VR horror game Phasmophobia including the items, ghosts, maps, tips, tricks and more.
show_downloads: False

navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup

links:
  section_1:
    - title: Home
      url: /
      key_trigger: 1
    - title: Items
      url: /items
      key_trigger: 2
    - title: Ghosts
      url: /ghosts
      key_trigger: 3
    - title: Maps
      url: /maps
      key_trigger: 4
    - title: Tips and tricks
      url: /tips-and-tricks
      key_trigger: 5
